name: Deploy to SFTP
on: push
jobs:
  Deploy-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing feedpiper repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive 
      - name: Initializing feedpiper-config repository - Delete default config folder
        run: rm -rf './config/'
      - name: Initializing feedpiper-config repository
        # This repository is meant to deploy my personal configuration stored in a separate repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          repository: kenijo/feedpiper-config
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: config
      - name: Initializing feedpiper-config repository - Rename configuration file
        continue-on-error: true
        run: mv './config/server-synology.conf.php' './config/conf.php'
      - name: Cleaning up - Delete files recursively from all subfolders
        run: |
          find . -name '.editorconfig' -type f -delete
          find . -name '.git' -type f -delete
          find . -name '.gitattributes' -type f -delete
          find . -name '.gitignore' -type f -delete
          find . -name '.gitmodules' -type f -delete
          find . -name '.travis.yml' -type f -delete
          find . -name 'composer.json' -type f -delete
          find . -name 'phpunit.xml.dist' -type f -delete
          find . -name '_config.yml' -type f -delete
      - name: Cleaning up - Delete specific files
        run: |
          rm -f './include/update_submodules.cmd'
      - name: Cleaning up - Delete folders recursively from all subfolders
        run: |
          find . -path '*/.git/*' -delete
          find . -type d -name '.git' -empty -delete
          find . -path '*/.github/*' -delete
          find . -type d -name '.github' -empty -delete
          find . -path '*/.vscode/*' -delete
          find . -type d -name '.vscode' -empty -delete
      - name: Cleaning up - Delete specific folders
        run: |
          rm -rf './include/parsedown/test/'
          rm -rf './include/simplepie/build/'
          rm -rf './include/simplepie/compatibility_test/'
          rm -rf './include/simplepie/demo/'
          rm -rf './include/simplepie/tests/'
      - name: Deploying to SFTP Server
        # https://github.com/marketplace/actions/ftp-deployer
        uses: sand4rt/ftp-deployer@v1.7
        with:
          sftp: true
          host: ${{ secrets.SYNOLOGY_SERVER_HOSTNAME }}
          port: ${{ secrets.SYNOLOGY_SERVER_PORT_SFTP }}
          username: ${{ secrets.SYNOLOGY_SERVER_USERNAME }}
          password: ${{ secrets.SYNOLOGY_SERVER_PASSWORD }}
          remote_folder: /web/feedpiper/
          local_folder: ./
          cleanup: true
