name: Deploy to SFTP
on: push
jobs:
  Deploy-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing feedpiper repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Composer vendor folder
        run: composer install
      - name: Initializing feedpiper-config repository - Delete default config folder
        run: rm -rf './config/'
      - name: Initializing feedpiper-config repository
        # This repository is meant to deploy my personal configuration stored in a separate repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          repository: kenijo/feedpiper-config
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: config
