name: Deploy to SFTP
on:
  #push:               # Triggers the workflow on push events but only for the master branch
  workflow_dispatch:  # Allows you to manually trigger the workflow
jobs:
  Deploy-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing feedpiper repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Importing Composer dependancies
        run: composer install

      - name: Cleanup what we do not want to upload
        run: |
          rm -rf './_config.yml'
          rm -rf './.git'
          rm -rf './.gitattributes'
          rm -rf './.github/'
          rm -rf './.gitignore'
          rm -rf './*.code-workspace'
          rm -rf './composer.json'
          rm -rf './composer.lock'
          rm -rf './vendor/simplehtmldom/simplehtmldom/example/'
          rm -rf './vendor/simplehtmldom/simplehtmldom/manual/'

      - name: Deploying to SFTP Server
        # https://github.com/marketplace/actions/sftp-uploader
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.SYNOLOGY_SERVER_HOSTNAME }}
          port: ${{ secrets.SYNOLOGY_SERVER_PORT_SFTP }}
          username: ${{ secrets.SYNOLOGY_SERVER_USERNAME }}
          password: ${{ secrets.SYNOLOGY_SERVER_PASSWORD }}
          localDir: './'
          remoteDir: '/web/feedpiper/'

      - name: Creating cache folder
        # https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SYNOLOGY_SERVER_HOSTNAME }}
          port: ${{ secrets.SYNOLOGY_SERVER_PORT_SFTP }}
          username: ${{ secrets.SYNOLOGY_SERVER_USERNAME }}
          password: ${{ secrets.SYNOLOGY_SERVER_PASSWORD }}
          script: |
            cd '/volume1/web/feedpiper/'
            mkdir -p './cache/'
            chmod 777 './cache/'
