on: push
name: Publish FeedPiper to netbox.w75.net
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
        submodules: true
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.BLACKHOST_FTP_SERVER }}
        ftp-username: ${{ secrets.BLACKHOST_FTP_USERNAME }}
        ftp-password: ${{ secrets.BLACKHOST_FTP_PASSWORD }}
