name: Deploy to SFTP
on: push
jobs:
  Deploy-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: Creating cache folder
        # https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SYNOLOGY_SERVER_HOSTNAME }}
          username: ${{ secrets.SYNOLOGY_SERVER_USERNAME }}
          password: ${{ secrets.SYNOLOGY_SERVER_PASSWORD }}
          port: ${{ secrets.SYNOLOGY_SERVER_PORT_SFTP }}
          script: |
            ls -al
            cd '/web/feedpiper/'
            mkdir './cache/'
            chmod 777 './cache/'